version: '3.8'
services:
  app:
    container_name: "biblio-gestion-BE"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mySqlPass
      - DB_NAME=bibliogestion
  
  db:
    container_name: "biblio-gestion-sql"
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bibliogestion
      MYSQL_ROOT_PASSWORD: mySqlPass
    volumes:
      - db-data:/var/lib/mysql
      - ./src/database/migrations/001_initial_setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: